trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
- group: spotar-tour-ios

steps:
- checkout: self
  persistCredentials: true
- script: |
    git config --global user.name "SWCode Developer"
    git config --global user.email "developers@swcode.io"
  displayName: 'Git config'
- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.4'
- task: CmdLine@2
  displayName: 'Install fastlane and other dependencies'
  inputs:
    script: 'bundle install'
- task: CmdLine@2
  displayName: 'Add pod source'
  inputs:
    script: |
      git config --global credential.helper store
      pod repo add sw-code "https://$(personalAccessToken)@github.com/sw-code/spotar-ios-pods"
      pod repo add sw-code-mapbox "https://$(personalAccessToken)@github.com/sw-code/flitsmeister-navigation-ios"
- task: CmdLine@2
  displayName: 'Add pod source'
  inputs:
    script: 
- task: CmdLine@2
  displayName: 'Update fastlane'
  inputs:
    script: 'bundle update fastlane'
- task: CmdLine@2
  displayName: 'Push pods'
  inputs:
    script: 'bundle exec fastlane bump_and_push_pods'
  env:
    GIT_PERSONAL_ACCESS_TOKEN: '$(personalAccessToken)@'