version: 2

workflows:
  version: 2
  default:
    jobs:
      - ios

step-library:
  - &generate-cache-key
      run:
        name: Generate cache key
        command: |
          echo "$(date +"%Y-%V")" > .circle-week
          ccache --clear
          ccache --max-size=5G

  - &restore-cache
      restore_cache:
        keys:
          - 'v3/{{ .Environment.CIRCLE_JOB }}/{{ arch }}/{{ .Branch }}/{{ checksum ".circle-week" }}'

  - &save-cache
      save_cache:
        key: 'v3/{{ .Environment.CIRCLE_JOB }}/{{ arch }}/{{ .Branch }}/{{ checksum ".circle-week" }}'
        paths: [ "Carthage" ]

  - &prepare
      run:
        name: Prepare
        command: |
          git submodule sync

jobs:
  ios:
    macos:
      xcode: "10.0.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    # Need to invoke bash as a login shell so that chruby is called to upgrade Ruby
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      # Set Ruby version to workaround https://github.com/CocoaPods/CocoaPods/issues/7447
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.4" > ~/.ruby-version
      - *prepare
      - *generate-cache-key
      - *restore-cache
      - *save-cache